/* CRIANDO A DATABASE */
CREATE DATABASE PRJ_INTEGRATION
GO


/* CONECTANDO A DATABASE */
USE PRJ_INTEGRATION
GO


/* CRIANDO UMA TABELA DE ORIGEM */
CREATE TABLE CLIENTES
(
    IDCLIENTE INT IDENTITY PRIMARY KEY
  , NOME      VARCHAR(30)
  , SEXO      CHAR(1)
  , EMAIL     VARCHAR(50)
)
GO


/* INSERINDO DADOS NA TABELA DE ORIGEM */
INSERT INTO CLIENTES (NOME, SEXO, EMAIL) VALUES ('FELICITY', 'F', 'FELICITY@GMAIL.COM')
INSERT INTO CLIENTES (NOME, SEXO, EMAIL) VALUES ('JOHN', 'M', 'JOHN@GMAIL.COM')
INSERT INTO CLIENTES (NOME, SEXO, EMAIL) VALUES ('OLIVER', 'M', 'OLIVER@GMAIL.COM')
INSERT INTO CLIENTES (NOME, SEXO, EMAIL) VALUES ('KAREN', 'F', 'KAREN@GMAIL.COM')
INSERT INTO CLIENTES (NOME, SEXO, EMAIL) VALUES ('BARREY', 'M', 'BARREY@GMAIL.COM')


/* SELECIONANDO OS DADOS INSERIDOS */
SELECT
	*
FROM
	CLIENTES
GO